version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: apusdrones
      MYSQL_DATABASE: apus_drones
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - /data/apusdronesdb:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - apusdrones

  backend:
    image: ${ECR_URI}:latest
    ports:
      - "8080:8080"
    networks:
      - apusdrones

networks:
  apusdrones:
