application:
  vars:
    default-delivery-price: 10
    grams-weight-limit: 2000.00
  base:
    url: localhost
server:
  error:
    include-message: always

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:apus_drones_embedded;MODE=MYSQL
  sql:
    init:
      platform: h2
  jpa:
    database-platform: org.hibernate.spatial.dialect.h2geodb.GeoDBDialect
    properties:
      hibernate:
        show_sql: true