application:
  vars:
    default-delivery-price: 10
    grams-weight-limit: 2000.00
  base:
    url: localhost

spring:
  datasource:
    url: jdbc:mysql://ad-db:3306/apus_drones
    username: apusdrones
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect