application:
  base:
    url: localhost
server:
  error:
    include-message: always
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:apus_drones_embedded
  jpa:
    show-sql: true