spring:
  profiles:
    active: local

aws:
  keys:
    accessKey: "AKIAQNTVEQCNERL3E7QR"
    secretKey: "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"
  s3:
    bucketName: apusdrone
jwt:
  secret: secretkey123
  token-validity: 18000
